services:
  - type: web
    name: facevital-flask
    runtime: python
    buildCommand: bash render-build.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
